#!/bin/bash

INIT() {
    rm -rf src
    mkdir src
    cd src
    git clone https://github.com/dctxmei/repo.git && cd repo
}
BUILD() {
    for ALL in $(ls -d */ | awk -F '/' '{print $1}'); do
        cd $ALL
        if [[ $? -ne 0 ]]; then
            (( I++ ))
            FAIL=$ALL
            echo $FAIL >> /tmp/GrepoG
            continue
        fi
        user-x86_64-build -c
        if [[ $? -ne 0 ]]; then
            (( I++ ))
            FAIL=$ALL
            echo $FAIL >> /tmp/GrepoG
            GARBAGE=$(pwd)
            cd ..
            rm -rf $GARBAGE
            continue
        fi
        mv *.pkg.tar.xz ..
        GARBAGE=$(pwd)
        cd ..
        rm -rf $GARBAGE
    done
}
DONE() {
    echo -e "\e[01m\e[31m"
    if [[ $I -eq 0 ]]; then
        echo "Build completed!"
        echo "Done :-)"
    else
        echo "Failed to build: $I"
        echo -ne "\e[0m"
        cat src/repo/.GG
        echo -ne "\e[31m"
        echo "> src/repo/.GG"
    fi
}

if [ $# -ge 1 ]; then
    if [[ $1 == "-o" || $1 == "--only" ]]; then
        if [[ $(cd $2; echo $?) -eq 0 ]]; then
            cd $2
            user-x86_64-build -c
        else
            exit 1
        fi
        exit 0
    fi
    exit 0
fi

INIT
BUILD
DONE
