#!/bin/bash

INIT() {
    rm -rf src
    mkdir src
    cd src
    git clone https://github.com/dctxmei/repo.git && cd repo
}
ALL() {
    for ALL in $(ls -d */ | awk -F '/' '{print $1}'); do
        cd $ALL
        if [[ $? -ne 0 ]]; then
            (( I++ ))
            FAIL=$ALL
            echo $FAIL >> src/repo/.GG
            continue
        fi
        user-x86_64-build -- -I /var/cache/pacman/pkg/git-*-x86_64.pkg.tar.xz
        if [[ $? -ne 0 ]]; then
            (( I++ ))
            FAIL=$ALL
            echo $FAIL >> src/repo/.GG
            GARBAGE=$(pwd)
            cd ..
            rm -rf $GARBAGE
            continue
        fi
        mv *.pkg.tar.xz ..
        GARBAGE=$(pwd)
        cd ..
        rm -rf $GARBAGE
    done
}
DONE() {
    echo -e "\e[01m\e[31m"
    if [[ $I -eq 0 ]]; then
        echo "Build completed!"
        echo "Done :-)"
    else
        echo "Failed to build: $I"
        echo -ne "\e[0m"
        cat src/repo/.GG
        echo -ne "\e[31m"
        echo "> src/repo/.GG"
    fi
}

INIT
ALL
DONE
