#!/bin/bash

for UPDATE in $(ls -d */ | awk -F '/' '{print $1}'); do
    test -e $UPDATE/.SRCINFO && continue
    mv $UPDATE .$UPDATE
    git clone https://aur.archlinux.org/$UPDATE.git || exit 1
    if [[ $? -eq 1 ]]; then
        mv .$UPDATE $UPDATE
    else
        test -e .$UPDATE/auto.sh && mv .$UPDATE/auto.sh $UPDATE
        rm -rf .$UPDATE
        rm -rf $UPDATE/.git*
        rm -f $UPDATE/.SRCINFO
    fi
done
